server:
  port: 8780


#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#服务的名称
spring:
  application:
    name: zuul-gw
    
zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
     
data-filter:
  auth-path: #valid token JwtAuthPreFilter
    - /user-service/user/**
  user-login-path: #login LoginAddJwtPostFilter
    - /user-service/login/**
  regPath: 
    - /user-service/reg/**